### ISSUE TITLE
Create download link

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/certificate#1]
In order to allow people to save the settings they created, create a download link.

Ideas:
- [x] The downloadable file should be html
- it can be generated by JavaScript
- [ ] Like the [index.html](https://github.com/CoderDojoPotsdam/CoderDojoPotsdam.github.io/blob/fb18cc1d269c012320c6e93967a8be34159d1c57/index.html) it redirects to https://coderdojopotsdam.github.io/certificate/index.html with options.
- [x] The options are the same as for the coderdojocertificate.svg
- [x] The options set the fields
- [x] The shown svg file is updated after the fields are set

**Comment by epodolsk** [comment]
I'd like to give this a try. To clarify, do you basically want the user to be able to download a file that redirects to the website with their chosen options already filled in? Would it be acceptable to pass the field values in the URL query string?

**Comment by niccokunzmann** [comment]
Hi, it is exactly as you said: The options are filled an and you can pass the by the parameters.

**Comment by niccokunzmann** [comment]
How did you find this issue?

**Comment by epodolsk** [comment]
I need to contribute to an open source project for a class, so I just searched for projects that needed help and found yours. 

I've sent a pull request with my changes. I'm very new to contributing to projects on GitHub so let me know if I've made a mistake somewhere. Thanks!

**Comment by niccokunzmann** [comment]
I will. Can you check that your changes work?

**Comment by niccokunzmann** [comment]
@epodolsk Cool! It works as I expected. I will create new issues with what I think can be included, too.
