### ISSUE TITLE
Style the front page (HTML/CSS)

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/certificate#2]
[The page](https://coderdojopotsdam.github.io/certificate/) looks really basic an dhas no styling.
Please improve it so you like it.

**Comment by AdamTheWizard** [comment]
Hey Nicco! 

I am really interested to help style this page for you. I am not sure what all the inputs are for though. Just to be clear do you just want a static page with those inputs placed in a more attractive way or am I missing something? 

thanks, Adam :)

**Comment by niccokunzmann** [comment]
Yes, exactly, I would like to have them placed in a way that you like best.
If you write somethig inside, you can see the text on the certificate.

**Comment by AdamTheWizard** [comment]
Perfect! I've already made a start but I will submit tomorrow after work when I've spent a little bit more time on it. Thanks for this :)



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by niccokunzmann** [comment]
You can also submit pull-requests with [WIP] = Work in Progress in the
title and #2 in the explanation.
This way, in rare cases, other people can discuss with you and jump in
and discuss.
I rarely see anyone doing this but it is possible :)

**Comment by AdamTheWizard** [comment]
Awesome. I'll probably use both of those relatively soon, so good advice! Just as one last question, is there anything you want me to avoid doing? I'm fairly competent with Bootstrap so I could implement that to improve overal style and responsiveness, unless yoh want it strictly html/css?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by niccokunzmann** [comment]
I would like to have it work offline too, and not retrieve resources
from the internet,
because I do not want users to be tracked.

**Comment by AdamTheWizard** [comment]
Hey Nicco,

I've forked the code, made changes to styling using just html and css and now I have no clue what to do with it. Apologies but I don't think I'll be able to help as this github website is a whole different beast! I'm beyond lost on this website and after spending all day using tutorials (for beginners) I still don't get it. The tutorials are crap and complicated and I'm abput as disheartened as possible!

Thanks for the opportunity to help out though, and if you want to view/review the code I've written I am happy to send over to you in any way thats best for you.

Adam



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by niccokunzmann** [comment]
Hi,

have you tried out the Github Desktop <https://desktop.github.com/> client?
It simplifies things a lot, like setup.
I am willing to help you over these first problems.
I remember using git the first time and it was not pleasant to
configure. The Github Client could make things easier.
Would you like to tell me, where you get stuck with it and upload a
screenshot, so I can tell you how to go on?

If you are too frustrated to ever go on, you can send the code to me via
email.

Best,
Nicco

**Comment by Alanh168** [comment]
Hi Nicco,
In terms of styling, I think the inputs should be grouped together on some left-side column and the preview should go on the right. That way people can actually see the entire preview (or most of it) as they type. 

In addition, I'll be changing the color scheme to something that matches a little better and adding font-weight to the p tags. The added font-weight will make them stand out more.

**Comment by niccokunzmann** [comment]
@Alanh168 Sure, please go ahead.

**Comment by niccokunzmann** [comment]
I think, we can close this. Thanks!

**Comment by niccokunzmann** [comment]
You can open more issues or pull-requests if you notice something.
