### ISSUE TITLE
Include name in the downloaded filename

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/certificate#6]
When the settings are saved, name it 

    settings-<NAME>.html

This way, we can distinct mutiple settings als know whom they are for.

**Comment by robert-gogolan** [comment]
Hi, I could take this on if you don't mind.

**Comment by niccokunzmann** [comment]
Hi, welcome. Great, sure, please go ahead. If you have any questions, you can ask here.

**Comment by Alanh168** [comment]
I believe this issue can be closed as well. Files are saved according to the user's inputted name.
